@extends('layouts.app')
@section('title','Beranda — Lumora') @section('heading','Halo, '.explode(' ',$user->name)[0].'!')
@section('content')
@if($user->role === 'student')
<section class="attendance-priority"><div class="attendance-copy"><span class="eyebrow">PRESENSI HARI INI</span><h2>Catat kehadiranmu</h2><p id="locationStatus">Aktifkan lokasi agar presensi tercatat dengan koordinat perangkat.</p></div><div class="attendance-clock"><strong id="liveClock">{{ now()->format('H:i') }}</strong><span>WIB</span><small>{{ now()->locale('id')->translatedFormat('d F Y') }}</small></div><div class="attendance-actions"><form method="post" action="{{ route('attendance.store') }}" class="attendance-form">@csrf<input type="hidden" name="action" value="check_in"><input type="hidden" name="latitude"><input type="hidden" name="longitude"><button class="attendance-button enter" {{ $todayAttendance?->check_in?'disabled':'' }}><i>↘</i><span><b>{{ $todayAttendance?->check_in?substr($todayAttendance->check_in,0,5):'Masuk' }}</b><small>{{ $todayAttendance?->check_in?'Sudah tercatat':'Catat sekarang' }}</small></span></button></form><form method="post" action="{{ route('attendance.store') }}" class="attendance-form">@csrf<input type="hidden" name="action" value="check_out"><input type="hidden" name="latitude"><input type="hidden" name="longitude"><button class="attendance-button leave" {{ !$todayAttendance?->check_in||$todayAttendance?->check_out?'disabled':'' }}><i>↗</i><span><b>{{ $todayAttendance?->check_out?substr($todayAttendance->check_out,0,5):'Pulang' }}</b><small>{{ $todayAttendance?->check_out?'Sudah tercatat':'Catat saat selesai' }}</small></span></button></form></div></section>
@elseif(in_array($user->role,['admin','teacher']))
<section class="attendance-overview"><div><span class="pulse-dot"></span><div><p class="eyebrow">PRESENSI LIVE</p><h2>{{ $stats[1][1] }} murid hadir hari ini</h2></div></div><a href="{{ route('attendance') }}">Pantau presensi →</a></section>
@endif

@if(in_array($user->role,['admin','teacher']))
<div class="hero"><div><span class="pill">TAHUN AJARAN 2026/2027</span><h2>{{ $user->role==='admin'?'Sekolah dalam kendali Anda.':'Siap menginspirasi hari ini?' }}</h2><p>{{ $user->role==='admin'?'Pantau aktivitas sekolah dan kelola operasional dari satu dashboard.':'Kelola kelas, tugas, dan perkembangan murid dengan lebih mudah.' }}</p></div><div class="hero-mark">L</div></div>
<div class="stats">@foreach($stats as $i=>$stat)<article class="stat-card"><div class="stat-icon s{{ $i }}">{{ ['◎','✓','▦','◈'][$i] }}</div><div><p>{{ $stat[0] }}</p><strong>{{ $stat[1] }}</strong><small>{{ $stat[2] }}</small></div></article>@endforeach</div>
<div class="grid-main"><section class="card"><div class="section-head"><div><p class="eyebrow">HARI INI</p><h3>Jadwal pembelajaran</h3></div><a href="{{ route('academics') }}">Lihat semua →</a></div><div class="timeline">@forelse($schedule as $item)<div class="timeline-item"><time>{{ substr($item->start_time,0,5) }}</time><i></i><div><b>{{ $item->subject }}</b><span>{{ $item->class_name }} · {{ $item->room_name }}</span></div><em>{{ substr($item->end_time,0,5) }}</em></div>@empty<p class="empty">Belum ada jadwal.</p>@endforelse</div></section><section class="card"><div class="section-head"><div><p class="eyebrow">TERBARU</p><h3>Pengumuman</h3></div></div><div class="announcements">@forelse($announcements as $item)<article><span>●</span><div><b>{{ $item->title }}</b><p>{{ $item->content }}</p><small>{{ \Carbon\Carbon::parse($item->published_at)->diffForHumans() }}</small></div></article>@empty<p class="empty">Belum ada pengumuman.</p>@endforelse</div></section></div>
@else
@if($user->role==='student')<section class="student-date-strip"><div><h2>Jadwal Minggu Ini</h2><span>Hari ini: {{ now()->locale('id')->translatedFormat('d F Y') }}</span></div><div class="week-days">@foreach($weekDates as $date)<div class="{{ $date->isToday()?'today':'' }}"><span>{{ $date->locale('id')->translatedFormat('D') }}</span><b>{{ $date->format('d') }}</b><i></i></div>@endforeach</div></section><div class="student-portal"><aside class="card todo-panel"><div class="section-head"><h2>Perlu Dikerjakan</h2><span class="count-pill">{{ $pendingWork->count() }}</span></div>@forelse($pendingWork as $work)<a href="{{ route('assignments') }}"><i>□</i><div><b>{{ $work->title }}</b><span>{{ $work->subject }}</span><small>Batas {{ \Carbon\Carbon::parse($work->due_date)->locale('id')->translatedFormat('d M Y, H:i') }}</small></div></a>@empty<div class="empty">Semua tugas sudah terkendali.</div>@endforelse</aside><section class="academic-classes"><div class="section-head"><div><p class="eyebrow">KELAS AKADEMIK</p><h2>Kelas yang kamu ikuti</h2></div><a href="{{ route('academics') }}">Lihat semua →</a></div><div class="student-class-grid">@forelse($studentClasses as $class)<a href="{{ route('learning.show',$class->id) }}" class="student-class-card"><span class="subject-mark">{{ strtoupper(substr($class->subject,0,2)) }}</span><h3>{{ $class->subject }}</h3><p>{{ $class->class_name }}</p><dl><div><dt>Guru</dt><dd>{{ $class->teacher }}</dd></div><div><dt>Jadwal</dt><dd>{{ $class->day }}, {{ substr($class->start_time,0,5) }}</dd></div></dl><div class="progress-label"><span>Kehadiran</span><b>96%</b></div><div class="progress"><i style="width:96%"></i></div></a>@empty<div class="card empty">Belum ada kelas akademik.</div>@endforelse</div></section></div>
@else<section class="simple-welcome"><span class="pill">TAHUN AJARAN 2026/2027</span><h2>Informasi sekolah untuk keluarga.</h2><p>Pantau agenda akademik dan informasi penting anak.</p></section><div class="children-grid">@foreach($children as $child)<article class="card"><span class="avatar large">{{ strtoupper(substr($child->name,0,1)) }}</span><div><h3>{{ $child->name }}</h3><p>{{ $child->class_name??'Belum memiliki rombel' }}</p><a href="{{ route('academics') }}">Lihat akademik anak →</a></div></article>@endforeach</div>@endif
@endif

<section class="calendar-dashboard"><div class="section-head"><div><p class="eyebrow">KALENDER AKADEMIK</p><h2>Agenda mendatang</h2></div><a href="{{ route('academics') }}">Buka jadwal lengkap →</a></div><div class="calendar-layout"><div class="calendar-events">@forelse($calendarEvents as $event)<article><time><b>{{ \Carbon\Carbon::parse($event->date_start)->format('d') }}</b><span>{{ \Carbon\Carbon::parse($event->date_start)->locale('id')->translatedFormat('M') }}</span></time><div><span class="calendar-type {{ $event->type }}">{{ ucfirst($event->type) }}</span><h3>{{ $event->title }}</h3><p>{{ \Carbon\Carbon::parse($event->date_start)->locale('id')->translatedFormat('d F Y') }}@if($event->date_start!=$event->date_end) – {{ \Carbon\Carbon::parse($event->date_end)->locale('id')->translatedFormat('d F Y') }}@endif</p></div></article>@empty<div class="empty">Belum ada agenda akademik.</div>@endforelse</div>@if($user->role==='student')<div class="student-week"><h3>Pelajaran mingguan</h3>@forelse($studentSchedule->groupBy('day') as $day=>$lessons)<div class="day-lessons"><b>{{ $day }}</b><div>@foreach($lessons as $lesson)<span><i></i>{{ substr($lesson->start_time,0,5) }} · {{ $lesson->subject }}</span>@endforeach</div></div>@empty<p class="empty">Belum terdaftar pada rombel aktif.</p>@endforelse</div>@endif</div></section>

@if(in_array($user->role,['admin','teacher']))
<section class="analytics-section" data-charts='@json($charts)'><div class="analytics-title"><div><p class="eyebrow">ANALITIK SEKOLAH</p><h2>Ringkasan dalam grafik</h2></div><span>Diperbarui hari ini</span></div><div class="chart-grid"><article class="card chart-card"><div class="chart-head"><div><h3>Tren kehadiran</h3><p>Persentase 7 hari terakhir</p></div><span class="trend up">↑ 4,8%</span></div><canvas id="lineChart" height="180"></canvas></article><article class="card chart-card"><div class="chart-head"><div><h3>Status presensi</h3><p>Komposisi hari ini</p></div></div><canvas id="pieChart" height="190"></canvas><div class="chart-legend"><span><i class="blue"></i>Hadir</span><span><i class="orange"></i>Terlambat</span><span><i class="purple"></i>Izin</span><span><i class="red"></i>Alpa</span></div></article><article class="card chart-card"><div class="chart-head"><div><h3>Realisasi SPP</h3></div></div><canvas id="columnChart" height="190"></canvas></article><article class="card chart-card"><div class="chart-head"><div><h3>Aktivitas pembelajaran</h3></div></div><canvas id="barChart" height="180"></canvas></article></div></section>
@endif
@endsection
