@extends('layouts.app')
@section('title',$session->subject.' — Lumora')
@section('heading',$session->subject)
@section('content')
<a href="{{ route('academics') }}" class="back-link">← Kembali ke Akademik</a>
<section class="learning-hero"><div><span class="eyebrow">{{ $session->class_name }}</span><h2>{{ $session->subject }}</h2><p>{{ $session->teacher }} · {{ $session->day }}, {{ substr($session->start_time,0,5) }}–{{ substr($session->end_time,0,5) }}</p></div><span class="subject-mark">{{ strtoupper(substr($session->subject,0,2)) }}</span></section>
@if(auth()->user()->role==='teacher' && auth()->id()==$session->teacher_id)
<section class="card meeting-builder"><div class="section-head"><div><p class="eyebrow">JADWAL PEMBELAJARAN</p><h2>Buat pertemuan</h2></div><span>Konten dikelola pada masing-masing pertemuan</span></div><div class="meeting-builder-grid">
<details><summary>＋ Satu pertemuan</summary><form method="post" action="{{ route('learning.meetings.store',$session->id) }}" class="compact-form">@csrf<input type="number" name="meeting_number" min="1" value="{{ ($meetings->max('meeting_number')??0)+1 }}" required><input name="title" placeholder="Judul pertemuan" required><input type="date" name="meeting_date" required><div class="form-row"><input type="time" name="start_time"><input type="time" name="end_time"></div><input name="location" placeholder="Ruang/lokasi"><select name="status"><option value="published">Publikasikan</option><option value="draft">Draft</option><option value="completed">Selesai</option></select><button class="primary-button small">Simpan pertemuan</button></form></details>
<details><summary>↻ Pertemuan berulang</summary><form method="post" action="{{ route('learning.meetings.recurring',$session->id) }}" class="compact-form">@csrf<input name="title" placeholder="Judul dasar pertemuan" required><div class="form-row"><label>Mulai<input type="date" name="date_start" required></label><label>Selesai<input type="date" name="date_end" required></label></div><select name="recurrence"><option value="weekly">Mingguan</option><option value="daily">Harian</option></select><div class="weekday-checks">@foreach(['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'] as $i=>$day)<label><input type="checkbox" name="days[]" value="{{ $i }}">{{ $day }}</label>@endforeach</div><div class="form-row"><input type="time" name="start_time" required><input type="time" name="end_time" required></div><input name="location" placeholder="Ruang/lokasi"><select name="status"><option value="published">Publikasikan</option><option value="draft">Draft</option></select><button class="primary-button small">Generate pertemuan</button></form></details>
</div></section>@endif
<div class="learning-layout"><section><div class="academic-tabs"><h2>Daftar pertemuan</h2><span>{{ $meetings->count() }} pertemuan</span></div><div class="meeting-list">
@forelse($meetings as $meeting)
@php $isTeacher=auth()->user()->role==='teacher' && auth()->id()==$session->teacher_id; $savedAttendance=collect($meetingAttendances[$meeting->id]??[])->keyBy('student_id'); @endphp
<article class="card meeting-card"><div class="meeting-number">{{ $meeting->meeting_number }}</div><div class="meeting-content"><span class="badge info">{{ ucfirst($meeting->status) }}</span><h3>{{ $meeting->title }}</h3><p>{{ \Carbon\Carbon::parse($meeting->meeting_date)->locale('id')->translatedFormat('l, d F Y') }}@if($meeting->start_time) · {{ substr($meeting->start_time,0,5) }}–{{ substr($meeting->end_time,0,5) }}@endif @if($meeting->location) · {{ $meeting->location }}@endif</p>
<div class="learning-resource-list">@foreach($materials[$meeting->id]??[] as $m)<a href="{{ route('materials.show',$m->id) }}">▤ Materi: {{ $m->title }} <small>Pratinjau →</small>@if($m->content)<span>{{ \Illuminate\Support\Str::limit($m->content,120) }}</span>@endif</a>@endforeach @foreach($assignments[$meeting->id]??[] as $a)<a href="{{ route('assignments') }}">□ Tugas: {{ $a->title }} <small>Buka →</small></a>@endforeach @foreach($quizzes[$meeting->id]??[] as $q)<a href="{{ route('quizzes.show',$q->id) }}">◇ Kuis: {{ $q->title }} <small>{{ $isTeacher?'Kelola soal':'Kerjakan' }} →</small></a>@endforeach @if(collect($materials[$meeting->id]??[])->isEmpty() && collect($assignments[$meeting->id]??[])->isEmpty() && collect($quizzes[$meeting->id]??[])->isEmpty())<p class="empty compact">Belum ada materi, tugas, atau kuis.</p>@endif</div>
@if($isTeacher)<div class="meeting-actions">
<details><summary>▤ Share materi</summary><form method="post" enctype="multipart/form-data" action="{{ route('learning.materials.store',$session->id) }}" class="compact-form">@csrf<input type="hidden" name="learning_meeting_id" value="{{ $meeting->id }}"><input name="title" placeholder="Judul materi" required><select name="type"><option value="document">Dokumen/file</option><option value="text">Teks</option><option value="link">Tautan</option><option value="video">Video</option></select><textarea name="content" placeholder="Isi atau ringkasan materi"></textarea><input name="url" type="url" placeholder="Tautan opsional"><label class="file-field">Upload PDF, gambar, Word, PPT, atau Excel<input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.ppt,.pptx,.xls,.xlsx"></label><button class="primary-button small">Bagikan materi</button></form></details>
<details><summary>□ Share tugas</summary><form method="post" action="{{ route('learning.assignments.store',$session->id) }}" class="compact-form">@csrf<input type="hidden" name="learning_meeting_id" value="{{ $meeting->id }}"><input name="title" placeholder="Judul tugas" required><textarea name="description" placeholder="Instruksi tugas"></textarea><label>Batas pengumpulan<input type="datetime-local" name="due_date" required></label><input type="number" name="max_score" value="100" min="1" max="1000"><button class="primary-button small">Bagikan tugas</button></form></details>
<details><summary>◇ Buat kuis PG</summary><form method="post" action="{{ route('learning.quizzes.store',$session->id) }}" class="compact-form">@csrf<input type="hidden" name="learning_meeting_id" value="{{ $meeting->id }}"><input name="title" placeholder="Judul kuis" required><input type="number" name="duration_minutes" value="30" min="1" max="300"><select name="status"><option value="published">Publikasikan</option><option value="draft">Draft</option></select><button class="primary-button small">Buat lalu isi soal</button></form></details>
<details class="attendance-editor"><summary>✓ Absen manual seluruh murid</summary><form method="post" action="{{ route('learning.attendance.store',[$session->id,$meeting->id]) }}">@csrf<div class="attendance-student-list">@foreach($students as $student)@php $record=$savedAttendance->get($student->id); @endphp<div><span><b>{{ $student->name }}</b><small>{{ $student->email }}</small></span><select name="statuses[{{ $student->id }}]">@foreach(['hadir'=>'Hadir','sakit'=>'Sakit','izin'=>'Izin','alpa'=>'Alfa'] as $value=>$label)<option value="{{ $value }}" @selected(($record->status??'hadir')===$value)>{{ $label }}</option>@endforeach</select><input name="notes[{{ $student->id }}]" value="{{ $record->note??'' }}" placeholder="Catatan opsional"></div>@endforeach</div><button class="primary-button small">Simpan presensi kelas</button></form></details>
</div>@endif</div></article>
@empty<div class="card empty">Belum ada pertemuan yang dipublikasikan.</div>@endforelse
</div></section><aside class="card roster"><div class="section-head"><h3>Murid di {{ $session->class_name }}</h3><span>{{ $students->count() }}</span></div>@foreach($students as $student)<div><span class="avatar mini">{{ strtoupper(substr($student->name,0,1)) }}</span><p><b>{{ $student->name }}</b><small>{{ $student->email }}</small></p></div>@endforeach</aside></div>
@endsection
