<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use App\Support\UserDataScope;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;

class LearningSessionController extends Controller
{
    private function assertMeeting(int $meetingId,int $sessionId): void { abort_unless(DB::table('learning_meetings')->where('id',$meetingId)->where('class_session_id',$sessionId)->exists(),422,'Pertemuan tidak sesuai dengan kelas ini.'); }
    private function assertCanManage(object $session, Request $request): void { abort_unless($request->user()->role==='teacher' && (int)$session->teacher_id===$request->user()->id,403,'Hanya guru pengampu yang dapat mengelola pembelajaran ini.'); }
    private function session(int $id, Request $request){ $s=DB::table('class_sessions')->join('school_classes','school_classes.id','=','class_sessions.school_class_id')->join('subjects','subjects.id','=','class_sessions.subject_id')->join('users as teachers','teachers.id','=','class_sessions.teacher_id')->where('class_sessions.id',$id)->select('class_sessions.*','school_classes.name as class_name','school_classes.homeroom_teacher_id','subjects.name as subject','teachers.name as teacher')->first(); abort_unless($s,404); $u=$request->user(); abort_unless($u->role==='admin'||UserDataScope::sessionIds($u)->contains($s->id),403); return $s; }
    public function show(int $session,Request $request){ $session=$this->session($session,$request); $user=$request->user(); $meetingQuery=DB::table('learning_meetings')->where('class_session_id',$session->id); if($user->isRole('student','parent'))$meetingQuery->where('status','published'); $meetings=$meetingQuery->orderBy('meeting_number')->get(); $ids=$meetings->pluck('id'); $materials=DB::table('materials')->whereIn('learning_meeting_id',$ids)->get()->groupBy('learning_meeting_id'); $assignments=$user->role==='admin'?collect():DB::table('assignments')->whereIn('learning_meeting_id',$ids)->get()->groupBy('learning_meeting_id'); $quizQuery=DB::table('quizzes')->whereIn('learning_meeting_id',$ids); if($user->isRole('student','parent'))$quizQuery->where('status','published'); $quizzes=$quizQuery->get()->groupBy('learning_meeting_id'); $studentQuery=DB::table('class_students')->join('users','users.id','=','class_students.student_id')->where('school_class_id',$session->school_class_id)->where('class_students.status','active'); if($user->isRole('student','parent'))$studentQuery->whereIn('users.id',UserDataScope::studentIds($user)); $students=$studentQuery->select('users.id','users.name','users.email')->orderBy('users.name')->get(); $meetingAttendances=DB::table('meeting_attendances')->whereIn('learning_meeting_id',$ids)->get()->groupBy('learning_meeting_id'); return view('academics.session',compact('session','meetings','materials','assignments','quizzes','students','meetingAttendances')); }
    public function meeting(int $session,Request $request){ $s=$this->session($session,$request); $this->assertCanManage($s,$request); $d=$request->validate(['meeting_number'=>'required|integer|min:1','title'=>'required|max:120','meeting_date'=>'required|date','start_time'=>'nullable|date_format:H:i','end_time'=>'nullable|date_format:H:i|after:start_time','location'=>'nullable|string|max:100','status'=>['required',Rule::in(['draft','published','completed'])]]); DB::table('learning_meetings')->insert($d+['class_session_id'=>$session,'created_by'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]); return back()->with('status','Pertemuan berhasil dibuat.'); }
    public function recurringMeetings(int $session,Request $request){$s=$this->session($session,$request);$this->assertCanManage($s,$request);$d=$request->validate(['title'=>'required|string|max:100','date_start'=>'required|date','date_end'=>'required|date|after_or_equal:date_start','recurrence'=>'required|in:daily,weekly','days'=>'nullable|array','days.*'=>'integer|between:0,6','start_time'=>'required|date_format:H:i','end_time'=>'required|date_format:H:i|after:start_time','location'=>'nullable|string|max:100','status'=>['required',Rule::in(['draft','published'])]]);$days=collect($d['days']??[])->map(fn($v)=>(int)$v);$number=(int)DB::table('learning_meetings')->where('class_session_id',$session)->max('meeting_number');$created=0;for($date=Carbon::parse($d['date_start']);$date->lte(Carbon::parse($d['date_end']))&&$created<366;$date->addDay()){if($d['recurrence']==='weekly'&&!$days->contains($date->dayOfWeek))continue;$number++;$ok=DB::table('learning_meetings')->insertOrIgnore(['class_session_id'=>$session,'meeting_number'=>$number,'title'=>$d['title'].' '.$number,'meeting_date'=>$date->toDateString(),'start_time'=>$d['start_time'],'end_time'=>$d['end_time'],'location'=>$d['location']??$s->room_name,'status'=>$d['status'],'created_by'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]);if($ok)$created++;else $number--;}return back()->with('status',$created.' pertemuan berulang berhasil dibuat.');}
    public function material(int $session,Request $request){ $s=$this->session($session,$request); $this->assertCanManage($s,$request); $d=$request->validate(['learning_meeting_id'=>'required|exists:learning_meetings,id','title'=>'required|max:150','type'=>['required',Rule::in(['text','link','video','document'])],'content'=>'nullable|max:5000','url'=>'nullable|url|max:1000','file'=>'nullable|file|mimes:pdf,jpg,jpeg,png,webp,doc,docx,ppt,pptx,xls,xlsx|max:10240']); $this->assertMeeting($d['learning_meeting_id'],$session); $file=$request->file('file'); unset($d['file']); if($file){$d['file_path']=$file->store('materials/'.$session,'public');$d['file_name']=$file->getClientOriginalName();$d['mime_type']=$file->getMimeType();} abort_if(empty($d['content'])&&empty($d['url'])&&!$file,422,'Isi, tautan, atau berkas materi wajib diisi.'); DB::table('materials')->insert($d+['uploaded_by'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]); return back()->with('status','Materi berhasil dibagikan dan dapat dipratinjau.'); }
    public function assignment(int $session,Request $request){ $s=$this->session($session,$request); $this->assertCanManage($s,$request); $d=$request->validate(['learning_meeting_id'=>'required|exists:learning_meetings,id','title'=>'required|max:150','description'=>'nullable|max:5000','due_date'=>'required|date','max_score'=>'required|integer|between:1,1000']); $this->assertMeeting($d['learning_meeting_id'],$session); DB::table('assignments')->insert($d+['class_session_id'=>$s->id,'created_at'=>now(),'updated_at'=>now()]); return back()->with('status','Tugas berhasil dibagikan.'); }
    public function quiz(int $session,Request $request){ $s=$this->session($session,$request); $this->assertCanManage($s,$request); $d=$request->validate(['learning_meeting_id'=>'required|exists:learning_meetings,id','title'=>'required|max:150','duration_minutes'=>'required|integer|between:1,300','status'=>['required',Rule::in(['draft','published'])]]); $this->assertMeeting($d['learning_meeting_id'],$session); DB::table('quizzes')->insert($d+['created_by'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]); return back()->with('status','Kuis berhasil dibuat.'); }
    private function materialRecord(int $id,Request $request){$m=DB::table('materials')->join('learning_meetings','learning_meetings.id','=','materials.learning_meeting_id')->where('materials.id',$id)->select('materials.*','learning_meetings.class_session_id','learning_meetings.title as meeting_title')->first();abort_unless($m,404);$this->session($m->class_session_id,$request);return $m;}
    public function materialPreview(int $material,Request $request){$material=$this->materialRecord($material,$request);return view('materials.show',compact('material'));}
    public function materialFile(int $material,Request $request){$material=$this->materialRecord($material,$request);abort_unless($material->file_path&&Storage::disk('public')->exists($material->file_path),404);return Storage::disk('public')->response($material->file_path,$material->file_name,['Content-Type'=>$material->mime_type,'Content-Disposition'=>'inline; filename="'.$material->file_name.'"']);}
    public function materialDownload(int $material,Request $request){$material=$this->materialRecord($material,$request);abort_unless($material->file_path&&Storage::disk('public')->exists($material->file_path),404);return Storage::disk('public')->download($material->file_path,$material->file_name);}
    public function attendance(int $session,int $meeting,Request $request){$s=$this->session($session,$request);$this->assertCanManage($s,$request);$this->assertMeeting($meeting,$session);$d=$request->validate(['statuses'=>'required|array','statuses.*'=>'required|in:hadir,sakit,izin,alpa','notes'=>'nullable|array','notes.*'=>'nullable|string|max:250']);$studentIds=DB::table('class_students')->where('school_class_id',$s->school_class_id)->where('status','active')->pluck('student_id');DB::transaction(function()use($d,$studentIds,$meeting,$request){foreach($studentIds as $studentId){if(!isset($d['statuses'][$studentId]))continue;DB::table('meeting_attendances')->updateOrInsert(['learning_meeting_id'=>$meeting,'student_id'=>$studentId],['status'=>$d['statuses'][$studentId],'note'=>$d['notes'][$studentId]??null,'recorded_by'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]);}});return back()->with('status','Presensi manual pertemuan berhasil disimpan.');}
}
