<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use App\Support\UserDataScope;

class LearningSessionController extends Controller
{
    private function assertMeeting(int $meetingId,int $sessionId): void { abort_unless(DB::table('learning_meetings')->where('id',$meetingId)->where('class_session_id',$sessionId)->exists(),422,'Pertemuan tidak sesuai dengan kelas ini.'); }
    private function session(int $id, Request $request){ $s=DB::table('class_sessions')->join('school_classes','school_classes.id','=','class_sessions.school_class_id')->join('subjects','subjects.id','=','class_sessions.subject_id')->join('users as teachers','teachers.id','=','class_sessions.teacher_id')->where('class_sessions.id',$id)->select('class_sessions.*','school_classes.name as class_name','school_classes.homeroom_teacher_id','subjects.name as subject','teachers.name as teacher')->first(); abort_unless($s,404); $u=$request->user(); abort_unless($u->role==='admin'||UserDataScope::sessionIds($u)->contains($s->id),403); return $s; }
    public function show(int $session,Request $request){ $session=$this->session($session,$request); $user=$request->user(); $meetingQuery=DB::table('learning_meetings')->where('class_session_id',$session->id); if($user->isRole('student','parent'))$meetingQuery->where('status','published'); $meetings=$meetingQuery->orderBy('meeting_number')->get(); $materials=DB::table('materials')->whereIn('learning_meeting_id',$meetings->pluck('id'))->get()->groupBy('learning_meeting_id'); $assignments=DB::table('assignments')->whereIn('learning_meeting_id',$meetings->pluck('id'))->get()->groupBy('learning_meeting_id'); $quizzes=DB::table('quizzes')->whereIn('learning_meeting_id',$meetings->pluck('id'))->where('status','published')->get()->groupBy('learning_meeting_id'); $studentQuery=DB::table('class_students')->join('users','users.id','=','class_students.student_id')->where('school_class_id',$session->school_class_id)->where('class_students.status','active'); if($user->isRole('student','parent'))$studentQuery->whereIn('users.id',UserDataScope::studentIds($user)); $students=$studentQuery->select('users.id','users.name','users.email')->orderBy('users.name')->get(); return view('academics.session',compact('session','meetings','materials','assignments','quizzes','students')); }
    public function meeting(int $session,Request $request){ $this->session($session,$request); $d=$request->validate(['meeting_number'=>'required|integer|min:1','title'=>'required|max:120','meeting_date'=>'required|date','status'=>['required',Rule::in(['draft','published','completed'])]]); DB::table('learning_meetings')->insert($d+['class_session_id'=>$session,'created_by'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]); return back()->with('status','Pertemuan berhasil dibuat.'); }
    public function material(int $session,Request $request){ $this->session($session,$request); $d=$request->validate(['learning_meeting_id'=>'required|exists:learning_meetings,id','title'=>'required|max:150','type'=>['required',Rule::in(['text','link','video','document'])],'content'=>'nullable|max:5000','url'=>'nullable|url|max:1000']); $this->assertMeeting($d['learning_meeting_id'],$session); DB::table('materials')->insert($d+['uploaded_by'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]); return back()->with('status','Materi berhasil dibagikan.'); }
    public function assignment(int $session,Request $request){ $s=$this->session($session,$request); $d=$request->validate(['learning_meeting_id'=>'required|exists:learning_meetings,id','title'=>'required|max:150','description'=>'nullable|max:5000','due_date'=>'required|date','max_score'=>'required|integer|between:1,1000']); $this->assertMeeting($d['learning_meeting_id'],$session); DB::table('assignments')->insert($d+['class_session_id'=>$s->id,'created_at'=>now(),'updated_at'=>now()]); return back()->with('status','Tugas berhasil dibagikan.'); }
    public function quiz(int $session,Request $request){ $this->session($session,$request); $d=$request->validate(['learning_meeting_id'=>'required|exists:learning_meetings,id','title'=>'required|max:150','duration_minutes'=>'required|integer|between:1,300','status'=>['required',Rule::in(['draft','published'])]]); $this->assertMeeting($d['learning_meeting_id'],$session); DB::table('quizzes')->insert($d+['created_by'=>$request->user()->id,'created_at'=>now(),'updated_at'=>now()]); return back()->with('status','Kuis berhasil dibuat.'); }
}
