<?php
namespace App\Http\Controllers;
use App\Support\UserDataScope;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class ModuleController extends Controller
{
    public function attendance(Request $request){ $ids=UserDataScope::studentIds($request->user()); return view('modules.attendance',['rows'=>DB::table('attendances')->join('users','users.id','=','attendances.student_id')->leftJoin('qr_stations','qr_stations.id','=','attendances.station_id')->whereIn('student_id',$ids)->select('attendances.*','users.name','qr_stations.label as station')->latest('attendances.created_at')->get(),'stations'=>$request->user()->isRole('admin','teacher')?DB::table('qr_stations')->where('status','active')->latest('opened_at')->get():collect()]); }
    public function academics(Request $request){ $user=$request->user(); return view('modules.academics',['sessions'=>DB::table('class_sessions')->join('subjects','subjects.id','=','class_sessions.subject_id')->join('school_classes','school_classes.id','=','class_sessions.school_class_id')->join('users','users.id','=','class_sessions.teacher_id')->whereIn('class_sessions.id',UserDataScope::sessionIds($user))->select('class_sessions.*','subjects.name as subject','school_classes.name as class_name','users.name as teacher')->orderByRaw("CASE day WHEN 'Senin' THEN 1 WHEN 'Selasa' THEN 2 WHEN 'Rabu' THEN 3 WHEN 'Kamis' THEN 4 WHEN 'Jumat' THEN 5 ELSE 6 END")->orderBy('start_time')->get(),'classes'=>DB::table('school_classes')->whereIn('id',UserDataScope::classIds($user))->orderBy('name')->get(),'subjects'=>DB::table('subjects')->orderBy('name')->get(),'teachers'=>DB::table('users')->where('role','teacher')->where('is_active',true)->orderBy('name')->get(),'years'=>DB::table('academic_years')->orderByDesc('is_active')->get(),'majors'=>DB::table('majors')->orderBy('name')->get(),'calendar'=>DB::table('school_calendar')->where(fn($q)=>$q->whereNull('target_role')->orWhere('target_role',$user->role))->orderBy('date_start')->get()]); }
    public function assignments(Request $request){ return view('modules.assignments',['assignments'=>DB::table('assignments')->join('class_sessions','class_sessions.id','=','assignments.class_session_id')->join('subjects','subjects.id','=','class_sessions.subject_id')->whereIn('class_session_id',UserDataScope::sessionIds($request->user()))->select('assignments.*','subjects.name as subject')->get()]); }
    public function finance(Request $request){ abort_if($request->user()->role==='teacher',403); return view('modules.finance',['bills'=>DB::table('spp_bills')->join('users','users.id','=','spp_bills.student_id')->whereIn('student_id',UserDataScope::studentIds($request->user()))->select('spp_bills.*','users.name')->latest('spp_bills.created_at')->get()]); }
}
