<?php
namespace App\Http\Controllers;
use App\Support\UserDataScope; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class QuizController extends Controller {
 private function quiz(int $id,Request $r){$q=DB::table('quizzes')->join('learning_meetings','learning_meetings.id','=','quizzes.learning_meeting_id')->join('class_sessions','class_sessions.id','=','learning_meetings.class_session_id')->join('subjects','subjects.id','=','class_sessions.subject_id')->where('quizzes.id',$id)->select('quizzes.*','learning_meetings.class_session_id','learning_meetings.title as meeting_title','class_sessions.teacher_id','subjects.name as subject')->first();abort_unless($q,404);abort_unless($r->user()->role==='admin'||UserDataScope::sessionIds($r->user())->contains($q->class_session_id),403);return $q;}
 public function show(Request $r,int $quiz){$quiz=$this->quiz($quiz,$r);$questions=DB::table('quiz_questions')->where('quiz_id',$quiz->id)->orderBy('id')->get()->map(function($q){$q->options=json_decode($q->options,true);return $q;});$attempt=$r->user()->role==='student'?DB::table('quiz_attempts')->where('quiz_id',$quiz->id)->where('student_id',$r->user()->id)->first():null;$attempts=$r->user()->role==='teacher'?DB::table('quiz_attempts')->join('users','users.id','=','quiz_attempts.student_id')->where('quiz_id',$quiz->id)->select('quiz_attempts.*','users.name')->latest('submitted_at')->get():collect();return view('quizzes.show',compact('quiz','questions','attempt','attempts'));}
 public function question(Request $r,int $quiz){$q=$this->quiz($quiz,$r);abort_unless($r->user()->role==='teacher'&&(int)$q->teacher_id===$r->user()->id,403);$d=$r->validate(['question_text'=>'required|string|max:2000','option_a'=>'required|string|max:1000','option_b'=>'required|string|max:1000','option_c'=>'required|string|max:1000','option_d'=>'required|string|max:1000','correct_option'=>'required|in:A,B,C,D','points'=>'required|integer|between:1,100']);DB::table('quiz_questions')->insert(['quiz_id'=>$q->id,'question_text'=>$d['question_text'],'options'=>json_encode(['A'=>$d['option_a'],'B'=>$d['option_b'],'C'=>$d['option_c'],'D'=>$d['option_d']]),'correct_option'=>$d['correct_option'],'points'=>$d['points'],'created_at'=>now(),'updated_at'=>now()]);return back()->with('status','Soal pilihan ganda berhasil ditambahkan.');}
 public function submit(Request $r,int $quiz){$q=$this->quiz($quiz,$r);abort_unless($r->user()->role==='student'&&$q->status==='published',403);abort_if(DB::table('quiz_attempts')->where('quiz_id',$q->id)->where('student_id',$r->user()->id)->exists(),422,'Kuis sudah pernah dikumpulkan.');$questions=DB::table('quiz_questions')->where('quiz_id',$q->id)->get();abort_if($questions->isEmpty(),422,'Kuis belum memiliki soal.');$answers=$r->validate(['answers'=>'required|array','answers.*'=>'nullable|in:A,B,C,D'])['answers'];DB::transaction(function()use($q,$questions,$answers,$r){$score=0;$max=$questions->sum('points');$attempt=DB::table('quiz_attempts')->insertGetId(['quiz_id'=>$q->id,'student_id'=>$r->user()->id,'score'=>0,'max_score'=>$max,'submitted_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);foreach($questions as $question){$selected=$answers[$question->id]??null;$correct=$selected===$question->correct_option;$points=$correct?$question->points:0;$score+=$points;DB::table('quiz_answers')->insert(['quiz_attempt_id'=>$attempt,'quiz_question_id'=>$question->id,'selected_option'=>$selected,'is_correct'=>$correct,'score'=>$points,'created_at'=>now(),'updated_at'=>now()]);}DB::table('quiz_attempts')->where('id',$attempt)->update(['score'=>$score,'updated_at'=>now()]);});return back()->with('status','Kuis berhasil dikumpulkan dan dinilai otomatis.');}
}
