<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#1E3A8A"><meta name="csrf-token" content="{{ csrf_token() }}"><script>if(localStorage.getItem('lumora-theme')==='dark'||(!localStorage.getItem('lumora-theme')&&matchMedia('(prefers-color-scheme:dark)').matches))document.documentElement.classList.add('dark')</script><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/logo_lumora.png"><title>@yield('title','Lumora')</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-slate-50 text-slate-800 antialiased">
<div class="min-h-screen lg:flex">
<aside class="sidebar hidden lg:flex"><a href="{{ route('dashboard') }}" class="brand"><img src="/logo_lumora.png" alt="Lumora"><span><b>Lumora</b><small>School Management</small></span></a>
<nav class="nav"><span class="nav-label">MENU UTAMA</span><a class="{{ request()->routeIs('dashboard')?'active':'' }}" href="{{ route('dashboard') }}">⌂ <span>Beranda</span></a><a class="{{ request()->routeIs('academics')?'active':'' }}" href="{{ route('academics') }}">▤ <span>Jadwal & Akademik</span></a><a class="{{ request()->routeIs('attendance')?'active':'' }}" href="{{ route('attendance') }}">✓ <span>Presensi</span></a><a class="{{ request()->routeIs('assignments')?'active':'' }}" href="{{ route('assignments') }}">□ <span>Tugas</span></a>@unless(auth()->user()->role==='teacher')<a class="{{ request()->routeIs('finance')?'active':'' }}" href="{{ route('finance') }}">◈ <span>Keuangan</span></a>@endunless @if(auth()->user()->role==='admin')<span class="nav-label">ADMINISTRASI</span><a class="{{ request()->routeIs('users.*')?'active':'' }}" href="{{ route('users.index') }}">♙ <span>Manajemen Pengguna</span></a>@endif</nav>
<div class="profile"><a href="{{ route('profile.edit') }}" class="avatar">@if(auth()->user()->photo)<img src="{{ Storage::url(auth()->user()->photo) }}" alt="Foto profil">@else{{ strtoupper(substr(auth()->user()->name,0,1)) }}@endif</a><a href="{{ route('profile.edit') }}" class="profile-name"><b>{{ auth()->user()->name }}</b><small>{{ ucfirst(auth()->user()->role) }} · Lihat profil</small></a><form action="{{ route('logout') }}" method="post">@csrf<button title="Keluar">↪</button></form></div></aside>
<main class="main"><header class="topbar"><div><button class="mobile-logo" id="menuButton">☰</button><p class="eyebrow">{{ now()->locale('id')->translatedFormat('l, d F Y') }}</p><h1>@yield('heading','Selamat datang')</h1></div><div class="top-actions"><button class="icon-button theme-toggle" id="themeToggle" title="Ganti tema"><span class="theme-icon">☾</span></button><div class="notification-wrap"><button class="icon-button" id="notificationButton" title="Notifikasi" aria-expanded="false">♢<span></span></button><div class="notification-dropdown" id="notificationDropdown"><div><b>Notifikasi</b><small>{{ $navNotifications->count() }} informasi terbaru</small></div>@forelse($navNotifications as $notice)<article><i></i><div><b>{{ $notice->title }}</b><p>{{ Str::limit($notice->content,70) }}</p><small>{{ \Carbon\Carbon::parse($notice->published_at)->diffForHumans() }}</small></div></article>@empty<p class="empty">Belum ada notifikasi.</p>@endforelse</div></div><a href="{{ route('profile.edit') }}" class="avatar">@if(auth()->user()->photo)<img src="{{ Storage::url(auth()->user()->photo) }}" alt="Foto profil">@else{{ strtoupper(substr(auth()->user()->name,0,1)) }}@endif</a></div></header>
@if(session('status'))<div class="alert success">✓ {{ session('status') }}</div>@endif
@if(session('error'))<div class="alert error">{{ session('error') }}</div>@endif
@if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif
<div class="content">@yield('content')</div></main></div>
<nav class="bottom-nav lg:hidden"><a href="{{ route('dashboard') }}">⌂<span>Beranda</span></a><a href="{{ route('academics') }}">▤<span>Jadwal</span></a><a href="{{ route('attendance') }}" class="scan">✓</a><a href="{{ route('assignments') }}">□<span>Tugas</span></a>@unless(auth()->user()->role==='teacher')<a href="{{ route('finance') }}">◈<span>Keuangan</span></a>@else<a href="{{ route('profile.edit') }}">♙<span>Profil</span></a>@endunless</nav>
</body></html>
