@extends('layouts.app')
@section('title','Kelas & Akademik — Lumora')
@section('heading',auth()->user()->role==='admin'?'Kelola Kelas':'Kelas Saya')
@section('content')
<div class="page-intro"><p>{{ auth()->user()->role==='admin'?'Atur rombel, mata pelajaran, wali kelas, guru pengampu, dan jadwal.':'Setiap kelas dipisahkan agar jadwal dan pembelajaran lebih mudah ditemukan.' }}</p></div>
@if(auth()->user()->role==='admin')
<section class="academic-admin"><details><summary>＋ Buat kelas/rombel</summary><form method="post" action="{{ route('academics.classes.store') }}" class="compact-form">@csrf<input name="name" placeholder="Contoh: XI IPA 2" required><input type="number" name="grade_level" min="1" max="12" placeholder="Tingkat" required><select name="academic_year_id" required>@foreach($years as $y)<option value="{{ $y->id }}">{{ $y->year_label }}</option>@endforeach</select><select name="major_id"><option value="">Tanpa jurusan</option>@foreach($majors as $m)<option value="{{ $m->id }}">{{ $m->name }}</option>@endforeach</select><select name="homeroom_teacher_id"><option value="">Pilih wali kelas</option>@foreach($teachers as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select><button class="primary-button small">Simpan rombel</button></form></details>
<details><summary>＋ Tambah mata pelajaran</summary><form method="post" action="{{ route('academics.subjects.store') }}" class="compact-form">@csrf<input name="name" placeholder="Nama mata pelajaran" required><input name="code" placeholder="Kode, contoh MAT" required><button class="primary-button small">Simpan mapel</button></form></details>
<details><summary>＋ Atur pelajaran & guru</summary><form method="post" action="{{ route('academics.sessions.store') }}" class="compact-form">@csrf<select name="school_class_id" required><option value="">Pilih rombel</option>@foreach($classes as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select><select name="subject_id" required><option value="">Pilih mapel</option>@foreach($subjects as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select><select name="teacher_id" required><option value="">Pilih guru</option>@foreach($teachers as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select><select name="day" required>@foreach(['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'] as $d)<option>{{ $d }}</option>@endforeach</select><input type="time" name="start_time" required><input type="time" name="end_time" required><input name="room_name" placeholder="Ruangan"><button class="primary-button small">Masukkan ke jadwal</button></form></details>
<details><summary>＋ Kalender akademik</summary><form method="post" action="{{ route('academics.calendar.store') }}" class="compact-form">@csrf<input name="title" placeholder="Nama agenda" required><select name="type"><option value="agenda">Agenda</option><option value="ujian">Ujian</option><option value="libur">Libur</option></select><input type="date" name="date_start" required><input type="date" name="date_end" required><select name="target_role"><option value="">Semua role</option><option value="teacher">Guru</option><option value="student">Murid</option><option value="parent">Wali</option></select><button class="primary-button small">Simpan agenda</button></form></details></section>
@endif

<div class="academic-tabs"><h2>{{ auth()->user()->role==='admin'?'Daftar kelas dan jadwal':'Kelas yang terhubung' }}</h2><span>{{ $classes->count() }} kelas · {{ $sessions->count() }} pelajaran</span></div>
<div class="separated-classes">@forelse($sessions->groupBy('class_id') as $classId=>$classSessions)<section class="class-section"><div class="class-section-head"><div><span class="subject-mark">{{ $classSessions->first()->class_name[0] }}</span><div><p class="eyebrow">ROMBONGAN BELAJAR</p><h2>{{ $classSessions->first()->class_name }}</h2></div></div><span>{{ $classSessions->count() }} mata pelajaran</span></div><div class="class-grid">@foreach($classSessions as $s)<article class="class-card"><div class="subject-icon">{{ strtoupper(substr($s->subject,0,2)) }}</div><span class="badge info">{{ $s->day }}</span><h3>{{ $s->subject }}</h3><p>{{ $s->teacher }} · {{ $s->room_name }}</p><div><span>{{ substr($s->start_time,0,5) }}–{{ substr($s->end_time,0,5) }}</span></div><a class="class-manage" href="{{ route('learning.show',$s->id) }}">{{ auth()->user()->role==='teacher'&&$s->teacher_id===auth()->id()?'Kelola pembelajaran':'Lihat pembelajaran' }} →</a></article>@endforeach</div></section>@empty<div class="card empty">Belum ada kelas yang terhubung.</div>@endforelse</div>
<section class="card calendar-table"><div class="section-head"><h2>Kalender akademik</h2></div><div class="calendar-events">@forelse($calendar as $event)<article><time><b>{{ \Carbon\Carbon::parse($event->date_start)->format('d') }}</b><span>{{ \Carbon\Carbon::parse($event->date_start)->locale('id')->translatedFormat('M') }}</span></time><div><span class="calendar-type {{ $event->type }}">{{ ucfirst($event->type) }}</span><h3>{{ $event->title }}</h3><p>{{ $event->date_start }} – {{ $event->date_end }}</p></div></article>@empty<div class="empty">Belum ada agenda kalender.</div>@endforelse</div></section>
@endsection
