@extends('layouts.app')
@section('title','Presensi — Lumora')
@section('heading','Kelola Presensi')
@section('content')
<div class="page-intro"><div><p>Rekap hadir, sakit, izin, dan alfa dari seluruh pengguna terkait.</p></div>@if(auth()->user()->isRole('admin','teacher'))<form method="post" action="{{ route('stations.store') }}" class="station-open-form">@csrf<input name="label" value="{{ auth()->user()->role==='admin'?'Gerbang Utama':'Kelas Saya' }}" required><select name="audience"><option value="student">QR Murid</option>@if(auth()->user()->role==='admin')<option value="teacher">QR Guru</option>@endif</select><button class="primary-button small">＋ Buka titik QR</button></form>@endif</div>
<div class="attendance-toolbar"><form method="get"><label>Tanggal<input type="date" name="date" value="{{ $date }}" onchange="this.form.submit()"></label></form><a href="{{ route('leave.index') }}" class="outline-button">Periksa izin & sakit →</a></div>
<div class="daily-summary"><article><i class="hadir">✓</i><span>Hadir<b>{{ $summary['hadir'] }}</b></span></article><article><i class="sakit">＋</i><span>Sakit<b>{{ $summary['sakit'] }}</b></span></article><article><i class="izin">▧</i><span>Izin<b>{{ $summary['izin'] }}</b></span></article><article><i class="alpa">×</i><span>Alfa<b>{{ $summary['alpa'] }}</b></span></article></div>
@if(auth()->user()->role==='teacher')<div class="attendance-rule"><b>Aturan guru</b><span>Guru harus presensi melalui QR admin sebelum membuka QR murid.</span></div>@endif
@if($stations->isNotEmpty())<div class="station-strip">@foreach($stations as $station)<a href="{{ route('stations.show',$station->id) }}"><span class="pulse-dot"></span><div><b>{{ $station->label }}</b><small>QR {{ $station->audience==='teacher'?'Guru':'Murid' }} · aktif {{ \Carbon\Carbon::parse($station->opened_at)->format('H:i') }}</small></div><em>Buka →</em></a>@endforeach</div>@endif
<section class="card table-card"><div class="section-head"><div><p class="eyebrow">REKAP {{ \Carbon\Carbon::parse($date)->locale('id')->translatedFormat('d F Y') }}</p><h3>Data presensi harian</h3></div></div><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Peran</th><th>Masuk/Pulang</th><th>Status</th><th>Sumber</th></tr></thead><tbody>@foreach($rows as $row)<tr><td><b>{{ $row->name }}</b></td><td>{{ $row->role==='teacher'?'Guru':'Murid' }}</td><td>{{ $row->check_in?substr($row->check_in,0,5):'—' }} / {{ $row->check_out?substr($row->check_out,0,5):'—' }}</td><td><span class="badge {{ $row->status }}">{{ ucfirst($row->status) }}</span></td><td>{{ $row->station??($row->status==='alpa'?'Tidak ada QR/pengajuan':'Pengajuan disetujui') }}</td></tr>@endforeach</tbody></table></div></section>
@endsection
